UPDATE `trinity_string` SET `content_loc8` = 'Команды доступные вам:' WHERE `entry` =9;
UPDATE `trinity_string` SET `content_loc8` = 'Игроков онлайн: %u (максимум: %u). Игроков в очереди: %u (максимум: %u).' WHERE `entry` =12;
UPDATE `trinity_string` SET `content_loc8` = 'Цель летает, вы не можете сделать этого.' WHERE `entry` =20;
UPDATE `trinity_string` SET `content_loc8` = 'Ваш пароль не может быть длиннее 16 знаков(ограничение клиента; пароль не изменен!' WHERE `entry` =25;
UPDATE `trinity_string` SET `content_loc8` = 'Вы находитесь: %s' WHERE `entry` =40;
UPDATE `trinity_string` SET `content_loc8` = 'Один или несколько параметров имеют неверные значения' WHERE `entry` =62;
UPDATE `trinity_string` SET `content_loc8` = 'Недопустимая цель' WHERE `entry` =63;
UPDATE `trinity_string` SET `content_loc8` = 'Вы не можете использовать здесь этот предмет.' WHERE `entry` =64;
UPDATE `trinity_string` SET `content_loc8` = 'Чтобы воспользоваться этим порталом необходимо достигнуть 58 уровня.' WHERE `entry` =65;
UPDATE `trinity_string` SET `content_loc8` = 'Глобальное уведомление: ' WHERE `entry` =100;
UPDATE `trinity_string` SET `content_loc8` = 'Карта: %u (%s) Зона: %u (%s) Область: %u (%s) Фаза: %u\nX: %f Y: %f Z: %f Ориентация: %f\nсетка[%u,%u]ячейка[%u,%u] ИНИнстанса: %u\n XЗоны: %f YЗоны: %f\nZОснования: %f ZПола: %f имеете данные Высот (Карта: %u КартаВ: %u)' WHERE `entry` =101;
UPDATE `trinity_string` SET `content_loc8` = 'Вы можете призвать игрока в ваше подземелье, только если он в Вашей группе, а вы лидер группы.' WHERE `entry` =103;
UPDATE `trinity_string` SET `content_loc8` = 'Вы не можете отправиться к игроку в подземелье, потому что вы сейчас в группе.' WHERE `entry` =104;
UPDATE `trinity_string` SET `content_loc8` = 'Вы можете отправиться в подземелье игрока, не находясь в его группе, только с включенным GM режимом.' WHERE `entry` =105;
UPDATE `trinity_string` SET `content_loc8` = 'Вы не можете отправиться к игроку %s из подземелья в подземелье.' WHERE `entry` =106;
UPDATE `trinity_string` SET `content_loc8` = 'Вы не можете призвать игрока %s из подземелья в подземелье.' WHERE `entry` =107;
UPDATE `trinity_string` SET `content_loc8` = 'Вы установили запас маны %s до %i/%i.' WHERE `entry` =120;
UPDATE `trinity_string` SET `content_loc8` = '%s установил запас Вашей маны до %i/%i.' WHERE `entry` =121;
UPDATE `trinity_string` SET `content_loc8` = 'Вы отдали свое ездовое животное %s.' WHERE `entry` =150;
UPDATE `trinity_string` SET `content_loc8` = '%s отдал вам свое ездовое животное.' WHERE `entry` =151;
UPDATE `trinity_string` SET `content_loc8` = '%s взял всю вашу медь.' WHERE `entry` =154;
UPDATE `trinity_string` SET `content_loc8` = '%s взял %i меди у вас.' WHERE `entry` =156;
UPDATE `trinity_string` SET `content_loc8` = '%s дал вам %i меди.' WHERE `entry` =158;
UPDATE `trinity_string` SET `content_loc8` = 'Удален бит(двоичный разряд) %i в поле %i.' WHERE `entry` =161;
UPDATE `trinity_string` SET `content_loc8` = 'Добавлен бит(двоичный разряд) %i в поле %i.' WHERE `entry` =162;
UPDATE `trinity_string` SET `content_loc8` = 'Нет подходящих вашему запросу локаций для телепортации.' WHERE `entry` =166;
UPDATE `trinity_string` SET `content_loc8` = 'Вы не можете телепортировать себя к себе!' WHERE `entry` =171;
UPDATE `trinity_string` SET `content_loc8` = 'Вы установили запас силы рун %s до %i/%i.' WHERE `entry` =173;
UPDATE `trinity_string` SET `content_loc8` = '%s установил запас Вашей силы рун до %i/%i.' WHERE `entry` =174;
UPDATE `trinity_string` SET `content_loc8` = 'Предмет ''%u'' (с ценой %u) уже в списке продавца.' WHERE `entry` =210;
UPDATE `trinity_string` SET `content_loc8` = 'Невозможно создать визуальную точку пути с ID существа: %d' WHERE `entry` =228;
UPDATE `trinity_string` SET `content_loc8` = 'Невозможно создать точку пути с ID: %d' WHERE `entry` =230;
UPDATE `trinity_string` SET `content_loc8` = 'Предупреждение: Невозможно удалить точку пути из мира с ID: %d' WHERE `entry` =242;
UPDATE `trinity_string` SET `content_loc8` = 'Это происходит, если точка пути слишком далеко от вашего персонажа.' WHERE `entry` =243;
UPDATE `trinity_string` SET `content_loc8` = 'Вы отключили %s чат на %u минут, эффективно при следующем входе игрока. Причина: %s.' WHERE `entry` =283;
UPDATE `trinity_string` SET `content_loc8` = 'Кол-во запросов: %i \r\nПоследние запросы: %s' WHERE `entry` =288;
UPDATE `trinity_string` SET `content_loc8` = 'Поступил новый запрос от %s' WHERE `entry` =289;
UPDATE `trinity_string` SET `content_loc8` = 'Дистанция спавна изменена на: %f' WHERE `entry` =297;
UPDATE `trinity_string` SET `content_loc8` = 'Время спавна изменено на: %i' WHERE `entry` =298;
UPDATE `trinity_string` SET `content_loc8` = 'дельта должна быть между 0 и %d (включительно)' WHERE `entry` =310;
UPDATE `trinity_string` SET `content_loc8` = ' [видимый]' WHERE `entry` =312;
UPDATE `trinity_string` SET `content_loc8` = ' [в войне]' WHERE `entry` =313;
UPDATE `trinity_string` SET `content_loc8` = ' [убран]' WHERE `entry` =315;
UPDATE `trinity_string` SET `content_loc8` = ' [не активен]' WHERE `entry` =317;
UPDATE `trinity_string` SET `content_loc8` = ' [нет репутации]' WHERE `entry` =327;
UPDATE `trinity_string` SET `content_loc8` = '  %s (GUID %u)' WHERE `entry` =329;
UPDATE `trinity_string` SET `content_loc8` = ' %s $gпочинил:починила; все ваши предметы.' WHERE `entry` =337;
UPDATE `trinity_string` SET `content_loc8` = 'Маршрут такси ID %u не найден!' WHERE `entry` =347;
UPDATE `trinity_string` SET `content_loc8` = 'Игровой объект (Entry: %u) имеет некорректные данные и не может быть заспавнен.' WHERE `entry` =348;
UPDATE `trinity_string` SET `content_loc8` = '%d (idx:%d) - |cffffffff|Htitle:%d|h[%s %s]|h|r %s %s ' WHERE `entry` =349;
UPDATE `trinity_string` SET `content_loc8` = '%d (idx:%d) - [%s %s] %s %s ' WHERE `entry` =350;
UPDATE `trinity_string` SET `content_loc8` = 'Звание не найдено!' WHERE `entry` =351;
UPDATE `trinity_string` SET `content_loc8` = 'Недопустимое звание ID: %u' WHERE `entry` =352;
UPDATE `trinity_string` SET `content_loc8` = 'Звание %u (%s) добавлено в список известных званий для игрока %s.' WHERE `entry` =353;
UPDATE `trinity_string` SET `content_loc8` = 'Звание %u (%s) удалено из списка известных званий для игрока %s.' WHERE `entry` =354;
UPDATE `trinity_string` SET `content_loc8` = 'Звание %u (%s) установлено как текущие из списка известных званий для игрока %s.' WHERE `entry` =355;
UPDATE `trinity_string` SET `content_loc8` = 'Текущее выбранное звание для игрока %s неизвестно и сброшено.' WHERE `entry` =356;
UPDATE `trinity_string` SET `content_loc8` = '%s установил ваш уровень доступа на %i.' WHERE `entry` =402;
UPDATE `trinity_string` SET `content_loc8` = 'У вас недостаточно прав доступа.' WHERE `entry` =403;
UPDATE `trinity_string` SET `content_loc8` = '%s $gполучил:получила; бан на %s. Причина: %s.' WHERE `entry` =408;
UPDATE `trinity_string` SET `content_loc8` = '%s $gполучил:получила; вечный бан за %s.' WHERE `entry` =409;
UPDATE `trinity_string` SET `content_loc8` = 'Следующие учетные записи соответствуют вашему запросу:' WHERE `entry` =428;
UPDATE `trinity_string` SET `content_loc8` = 'Неверный ID предмета: %u' WHERE `entry` =435;
UPDATE `trinity_string` SET `content_loc8` = 'Оставшееся время бана: %s, Забанен: %s, Причина: %s' WHERE `entry` =453;
UPDATE `trinity_string` SET `content_loc8` = 'Поврежденная команда, пожайлуста проверьте базу данных' WHERE `entry` =455;
UPDATE `trinity_string` SET `content_loc8` = 'ID: %d %s effmask: %d Зарядов: %d Стаков: %d Слот: %d Длительность: %d Максимальная длительность: %d %s %s caster: %s guid: %d' WHERE `entry` =468;
UPDATE `trinity_string` SET `content_loc8` = 'Дамп персонажа успешно создан!' WHERE `entry` =481;
UPDATE `trinity_string` SET `content_loc8` = 'Дамп персонажа создать не удалось!' WHERE `entry` =482;
UPDATE `trinity_string` SET `content_loc8` = 'Заклинание %u не работает и не доступно для применения или изучения!' WHERE `entry` =483;
UPDATE `trinity_string` SET `content_loc8` = 'Игрок %s должен иметь навык %u (%s; прежде чем использовать эту команду.' WHERE `entry` =485;
UPDATE `trinity_string` SET `content_loc8` = 'Неверный ID навыка (%u)' WHERE `entry` =486;
UPDATE `trinity_string` SET `content_loc8` = '%s уже знает это заклинание.' WHERE `entry` =489;
UPDATE `trinity_string` SET `content_loc8` = 'Перезарядка всех заклинаний у %s завершена.' WHERE `entry` =492;
UPDATE `trinity_string` SET `content_loc8` = 'Перезарядка заклинания %u у %s завершена.' WHERE `entry` =493;
UPDATE `trinity_string` SET `content_loc8` = 'Команда : Additem, ID предмета = %i, кол-во = %i' WHERE `entry` =494;
UPDATE `trinity_string` SET `content_loc8` = 'Команда : Additemset, ID комплекта предметов  = %i' WHERE `entry` =495;
UPDATE `trinity_string` SET `content_loc8` = 'Предмет (ID = %i, кол-во = %i) убран у %s' WHERE `entry` =496;
UPDATE `trinity_string` SET `content_loc8` = 'Невозможно создать предмет ''%i'' (кол-во: %i)' WHERE `entry` =497;
UPDATE `trinity_string` SET `content_loc8` = 'Вы должны ввести имя гильдии!' WHERE `entry` =498;
UPDATE `trinity_string` SET `content_loc8` = 'Гильдия не создана! (уже существует?)' WHERE `entry` =501;
UPDATE `trinity_string` SET `content_loc8` = 'Не найдены вещи из комплекта ''%u''.' WHERE `entry` =502;
UPDATE `trinity_string` SET `content_loc8` = 'Расстояние: (3D) %f (2D) %f (Точно 3D) %f (Точно 2D) %f ярд(ов).' WHERE `entry` =503;
UPDATE `trinity_string` SET `content_loc8` = 'Неверный тип ссылки!' WHERE `entry` =511;
UPDATE `trinity_string` SET `content_loc8` = '%d - |cffffffff|Hitem:%d:0:0:0:0:0:0:0:0|h[%s]|h|r ' WHERE `entry` =512;
UPDATE `trinity_string` SET `content_loc8` = '%d (Entry: %d) - |cffffffff|Hgameobject:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r ' WHERE `entry` =517;
UPDATE `trinity_string` SET `content_loc8` = 'Игровой объект (Entry: %u) не найден' WHERE `entry` =522;
UPDATE `trinity_string` SET `content_loc8` = 'Выбранный объект:\n|cffffffff|Hgameobject:%d|h[%s]|h|r GUID: %u ID: %u\nX: %f Y: %f Z: %f MapId: %u\nОриентация: %f\nPhasemask %u' WHERE `entry` =524;
UPDATE `trinity_string` SET `content_loc8` = '%s (lowguid: %u) генератор движения cтаков:' WHERE `entry` =526;
UPDATE `trinity_string` SET `content_loc8` = '   Случайный' WHERE `entry` =528;
UPDATE `trinity_string` SET `content_loc8` = '   Точка пути' WHERE `entry` =529;
UPDATE `trinity_string` SET `content_loc8` = '   Беспорядочный' WHERE `entry` =531;
UPDATE `trinity_string` SET `content_loc8` = '   Следовать за игроком %s (lowguid %u)' WHERE `entry` =532;
UPDATE `trinity_string` SET `content_loc8` = '   Следовать за существом %s (lowguid %u)' WHERE `entry` =533;
UPDATE `trinity_string` SET `content_loc8` = '   Следовать за <NULL>' WHERE `entry` =534;
UPDATE `trinity_string` SET `content_loc8` = '   Неизвестный генератор движения (%u)' WHERE `entry` =538;
UPDATE `trinity_string` SET `content_loc8` = 'Игрок выбрал NPC\r\nDB GUID: %u, Текущий GUID: %u.\r\nФракция: %u.\r\nнпцФлаг: %u.\r\nEntry: %u.\r\nДисплейID: %u (Текущий: %u).' WHERE `entry` =539;
UPDATE `trinity_string` SET `content_loc8` = 'ИНИнстанса: %u' WHERE `entry` =547;
UPDATE `trinity_string` SET `content_loc8` = 'Оставшееся время молчанки: %s' WHERE `entry` =550;
UPDATE `trinity_string` SET `content_loc8` = '%s больше не имеет территорий для исследования.' WHERE `entry` =552;
UPDATE `trinity_string` SET `content_loc8` = '%s $gоткрыл:открыла; все территории для вас.' WHERE `entry` =553;
UPDATE `trinity_string` SET `content_loc8` = '%s $gзакрыл:закрыла; все открытые территории у вас.' WHERE `entry` =554;
UPDATE `trinity_string` SET `content_loc8` = 'Выбраный игрок или существо не имеет атакуемой цели.' WHERE `entry` =579;
UPDATE `trinity_string` SET `content_loc8` = '$n $gзахватил:захватила; флаг Орды!' WHERE `entry` =605;
UPDATE `trinity_string` SET `content_loc8` = '$n $gзахватил:захватила; флаг Альянса!' WHERE `entry` =606;
UPDATE `trinity_string` SET `content_loc8` = '$n $gпотерял:потеряла; флаг Орды!' WHERE `entry` =607;
UPDATE `trinity_string` SET `content_loc8` = '$n $gпотерял:потеряла; флаг Альянса!' WHERE `entry` =608;
UPDATE `trinity_string` SET `content_loc8` = '$n $gвернул:вернула; флаг Альянса на свою базу!' WHERE `entry` =609;
UPDATE `trinity_string` SET `content_loc8` = '$n $gвернул:вернула; флаг Орды на свою базу!' WHERE `entry` =610;
UPDATE `trinity_string` SET `content_loc8` = '$n $gподобрал:подобрала; флаг Орды!' WHERE `entry` =611;
UPDATE `trinity_string` SET `content_loc8` = '$n $gподобрал:подобрала; флаг Альянса!' WHERE `entry` =612;
UPDATE `trinity_string` SET `content_loc8` = 'стойла' WHERE `entry` =652;
UPDATE `trinity_string` SET `content_loc8` = 'кузницу' WHERE `entry` =653;
UPDATE `trinity_string` SET `content_loc8` = 'ферму' WHERE `entry` =654;
UPDATE `trinity_string` SET `content_loc8` = 'лесопилку' WHERE `entry` =655;
UPDATE `trinity_string` SET `content_loc8` = 'золотой рудник' WHERE `entry` =656;
UPDATE `trinity_string` SET `content_loc8` = '%s $gзахватил:захватила; %s!' WHERE `entry` =657;
UPDATE `trinity_string` SET `content_loc8` = '$n $gзащитил:защитила; %s!' WHERE `entry` =658;
UPDATE `trinity_string` SET `content_loc8` = '$n $gосадил:осадила; %s!' WHERE `entry` =659;
UPDATE `trinity_string` SET `content_loc8` = '$n претендует на захват %s! Если никто не вмешается, то через 1 минуту %s получит контроль над точкой!' WHERE `entry` =660;
UPDATE `trinity_string` SET `content_loc8` = 'Битва за Низину Арати начнется через 1 минуту!' WHERE `entry` =661;
UPDATE `trinity_string` SET `content_loc8` = 'Битва за Низину Арати начнется через 30 секунд. Приготовьтесь!' WHERE `entry` =662;
UPDATE `trinity_string` SET `content_loc8` = 'Битва за Низину Арати началась!' WHERE `entry` =663;
UPDATE `trinity_string` SET `content_loc8` = '%s желает, чтобы $gего:её; не беспокоили, и не может принимать сообщения: %s' WHERE `entry` =707;
UPDATE `trinity_string` SET `content_loc8` = '%s $gотошел:отошла;: %s' WHERE `entry` =708;
UPDATE `trinity_string` SET `content_loc8` = '$gOтошел:Oтошла;' WHERE `entry` =710;
UPDATE `trinity_string` SET `content_loc8` = 'Карта: %s, Область: %s, Зона: %s, Фаза: %u' WHERE `entry` =714;
UPDATE `trinity_string` SET `content_loc8` = 'Карта: %s, Область: %s' WHERE `entry` =716;
UPDATE `trinity_string` SET `content_loc8` = '|cffff0000[Анонс Арены]:|r %s -- Присоединились : %ux%u : %u|r' WHERE `entry` =718;
UPDATE `trinity_string` SET `content_loc8` = '|cffff0000[Анонс Арены]:|r %s -- Вышли : %ux%u : %u|r' WHERE `entry` =719;
UPDATE `trinity_string` SET `content_loc8` = 'Тип сражений на арене сменен на 1v1 для отладки. Не вставайте в очередь в группе.' WHERE `entry` =737;
UPDATE `trinity_string` SET `content_loc8` = 'Обновление очков Арены для всех персонажей в сети завершено.' WHERE `entry` =743;
UPDATE `trinity_string` SET `content_loc8` = 'Арены были отключены. Вы не можете встать в очередь.' WHERE `entry` =748;
UPDATE `trinity_string` SET `content_loc8` = '%s $gзащитил:защитила; крепость!' WHERE `entry` =757;
UPDATE `trinity_string` SET `content_loc8` = '%s $gзахватил:захватила; крепость!' WHERE `entry` =758;
UPDATE `trinity_string` SET `content_loc8` = '%s башня повреждена!' WHERE `entry` =761;
UPDATE `trinity_string` SET `content_loc8` = '%s башня уничтожена!' WHERE `entry` =762;
UPDATE `trinity_string` SET `content_loc8` = 'Вы достигли Ранга 2: Лейтенант' WHERE `entry` =772;
UPDATE `trinity_string` SET `content_loc8` = 'До битвы на  Озере Ледяных Оков осталось 30 минут!' WHERE `entry` =780;
UPDATE `trinity_string` SET `content_loc8` = 'До битвы на  Озере Ледяных Оков осталось 10 минут! Портал с Даларана начнет работу во время боя.' WHERE `entry` =781;
UPDATE `trinity_string` SET `content_loc8` = 'Битва за Озеро Ледяных Оков Остановлена. Не хватает защитников. Крепость переходит атакующей  стороне.' WHERE `entry` =782;
UPDATE `trinity_string` SET `content_loc8` = 'Битва за Озеро Ледяных Оков Остановлена. Не хватает нападающих. Крепость остается защитникам.' WHERE `entry` =783;
UPDATE `trinity_string` SET `content_loc8` = '|Hplayer:$N|h[$N]|h $gполучил:получила; достижение $a!' WHERE `entry` =810;
UPDATE `trinity_string` SET `content_loc8` = 'Entry %u не найден в таблице creature_template.' WHERE `entry` =817;
UPDATE `trinity_string` SET `content_loc8` = 'Город' WHERE `entry` =819;
UPDATE `trinity_string` SET `content_loc8` = 'Аккаунт %s не может быть удалён (возможно формат sql файла был обновлён)' WHERE `entry` =1007;
UPDATE `trinity_string` SET `content_loc8` = '-[         Аккаунт][   Персонаж][             IP][Карта][Зона][Exp][ГМ Ур]-' WHERE `entry` =1010;
UPDATE `trinity_string` SET `content_loc8` = '-[%16s][%12s][%15s][%3d][%4d][%d][%d]-' WHERE `entry` =1013;
UPDATE `trinity_string` SET `content_loc8` = 'Нет игроков онлайн.' WHERE `entry` =1014;
UPDATE `trinity_string` SET `content_loc8` = '-======================== Игроки онлайн =======================-' WHERE `entry` =1015;
UPDATE `trinity_string` SET `content_loc8` = '| GUID       | Имя                 | Аккаунт                      | Дата Удаления         |' WHERE `entry` =1016;
UPDATE `trinity_string` SET `content_loc8` = 'Персонажи не найдены. ' WHERE `entry` =1019;
UPDATE `trinity_string` SET `content_loc8` = 'Восстанавливаем следующих персонажей:' WHERE `entry` =1020;
UPDATE `trinity_string` SET `content_loc8` = 'Удаляем следующих персонажей:' WHERE `entry` =1021;
UPDATE `trinity_string` SET `content_loc8` = 'Персонажа ''%s'' (GUID: %u Аккаунт %u) невозможно восстановить: аккаунт не существует!' WHERE `entry` =1023;
UPDATE `trinity_string` SET `content_loc8` = 'Персонажа ''%s'' (GUID: %u Аккаунт %u) невозможно восстановить: максимальный лимит персонажей на аккаунте исчерпан' WHERE `entry` =1024;
UPDATE `trinity_string` SET `content_loc8` = 'Персонажа ''%s'' (GUID: %u Аккаунт %u) невозможно восстановить: новое имя уже используется!' WHERE `entry` =1025;
UPDATE `trinity_string` SET `content_loc8` = 'GUID: %u Имя: %s Аккаунт: %s (%u) Дата: %s' WHERE `entry` =1026;
UPDATE `trinity_string` SET `content_loc8` = 'Сообщение дня изменено на:\r\n%s' WHERE `entry` =1101;
UPDATE `trinity_string` SET `content_loc8` = 'Файл дампа повреждён!' WHERE `entry` =1114;
UPDATE `trinity_string` SET `content_loc8` = 'Вы сменили пол персонажа с %s на %s.' WHERE `entry` =1120;
UPDATE `trinity_string` SET `content_loc8` = 'Неверный тип питомца' WHERE `entry` =1124;
UPDATE `trinity_string` SET `content_loc8` = 'Ваш питомец выучил все таланты.' WHERE `entry` =1125;
UPDATE `trinity_string` SET `content_loc8` = 'Таланты Вашего питомца были сброшены.' WHERE `entry` =1126;
UPDATE `trinity_string` SET `content_loc8` = 'Таланты для %s питомца сброшены' WHERE `entry` =1127;
UPDATE `trinity_string` SET `content_loc8` = 'Забаненных персонажей на текущий момент:' WHERE `entry` =1132;
UPDATE `trinity_string` SET `content_loc8` = '|   Персонаж   |   Дата Бана    |   Дата Разбана  |  Выдан ГМом   |   Причина Бана  |' WHERE `entry` =1133;
UPDATE `trinity_string` SET `content_loc8` = 'Отправка тикетов не допускается.' WHERE `entry` =1134;
UPDATE `trinity_string` SET `content_loc8` = 'Отправка тикетов не разрешена.' WHERE `entry` =1135;
UPDATE `trinity_string` SET `content_loc8` = 'Персонаж %s никогда не $gблокировался:блокировалась;!' WHERE `entry` =1136;
UPDATE `trinity_string` SET `content_loc8` = 'Вы хотите просмотреть ролик %u, но его не существует.' WHERE `entry` =1201;
UPDATE `trinity_string` SET `content_loc8` = 'Битва начнется через 2 минуты.' WHERE `entry` =1205;
UPDATE `trinity_string` SET `content_loc8` = 'Битва начнется через 1 минуту.' WHERE `entry` =1206;
UPDATE `trinity_string` SET `content_loc8` = 'Битва начнется через 30 секунд.' WHERE `entry` =1207;
UPDATE `trinity_string` SET `content_loc8` = 'Начался бой!' WHERE `entry` =1208;
UPDATE `trinity_string` SET `content_loc8` = 'крепости Альянса' WHERE `entry` =1209;
UPDATE `trinity_string` SET `content_loc8` = 'крепости Орды' WHERE `entry` =1210;
UPDATE `trinity_string` SET `content_loc8` = '%s побеждает!' WHERE `entry` =1211;
UPDATE `trinity_string` SET `content_loc8` = 'Западные ворота %s разрушены!' WHERE `entry` =1212;
UPDATE `trinity_string` SET `content_loc8` = 'Восточные ворота %s разрушены!' WHERE `entry` =1213;
UPDATE `trinity_string` SET `content_loc8` = 'Южные ворота %s разрушены!' WHERE `entry` =1214;
UPDATE `trinity_string` SET `content_loc8` = 'Северные ворота %s разрушены!' WHERE `entry` =1215;
UPDATE `trinity_string` SET `content_loc8` = '$n $gосадил:осадила; %s' WHERE `entry` =1216;
UPDATE `trinity_string` SET `content_loc8` = '$n $gзащитил:защитила; %s' WHERE `entry` =1217;
UPDATE `trinity_string` SET `content_loc8` = '$n претендует на захват %s! Если никто не вмешается, то через 1 минуту %s получит контроль над точкой!' WHERE `entry` =1218;
UPDATE `trinity_string` SET `content_loc8` = '%s $gзахватил:захватила; %s' WHERE `entry` =1219;
UPDATE `trinity_string` SET `content_loc8` = 'Мастерские' WHERE `entry` =1220;
UPDATE `trinity_string` SET `content_loc8` = 'Доки' WHERE `entry` =1221;
UPDATE `trinity_string` SET `content_loc8` = 'Нефтезавод' WHERE `entry` =1222;
UPDATE `trinity_string` SET `content_loc8` = 'Каменоломни' WHERE `entry` =1223;
UPDATE `trinity_string` SET `content_loc8` = 'Ангар' WHERE `entry` =1224;
UPDATE `trinity_string` SET `content_loc8` = 'Альянс' WHERE `entry` =1225;
UPDATE `trinity_string` SET `content_loc8` = 'Орда' WHERE `entry` =1226;
UPDATE `trinity_string` SET `content_loc8` = '%s под атакой! Если их не остановить, %s уничтожит это!' WHERE `entry` =1303;
UPDATE `trinity_string` SET `content_loc8` = '%s $gзанял:заняла; %s' WHERE `entry` =1304;
UPDATE `trinity_string` SET `content_loc8` = '%s $gзанял:заняла; %s' WHERE `entry` =1305;
UPDATE `trinity_string` SET `content_loc8` = '%s $gзанял:заняла; %s' WHERE `entry` =1306;
UPDATE `trinity_string` SET `content_loc8` = '%s под атакой! Если их не остановить, %s захватит это!' WHERE `entry` =1307;
UPDATE `trinity_string` SET `content_loc8` = '%s $gзанял:заняла; %s! Теперь эти ресурсы используются для подкрепления!' WHERE `entry` =1308;
UPDATE `trinity_string` SET `content_loc8` = 'Это подземелье закрыто.' WHERE `entry` =5008;
UPDATE `trinity_string` SET `content_loc8` = 'Броня: %u' WHERE `entry` =5021;
UPDATE `trinity_string` SET `content_loc8` = 'Тип: %u' WHERE `entry` =5025;
UPDATE `trinity_string` SET `content_loc8` = 'ДисплейID: %u' WHERE `entry` =5026;
UPDATE `trinity_string` SET `content_loc8` = 'ЛутID: %u' WHERE `entry` =5028;
UPDATE `trinity_string` SET `content_loc8` = 'Орда захватила Западный Маяк!' WHERE `entry` =10013;
UPDATE `trinity_string` SET `content_loc8` = 'Альянс захватил Западный Маяк!' WHERE `entry` =10014;
UPDATE `trinity_string` SET `content_loc8` = 'Орда захватила Восточный Маяк!' WHERE `entry` =10015;
UPDATE `trinity_string` SET `content_loc8` = 'Альянс захватил Восточный Маяк!' WHERE `entry` =10016;
UPDATE `trinity_string` SET `content_loc8` = 'Орда захватила кладбище Двух Шпилей!' WHERE `entry` =10017;
UPDATE `trinity_string` SET `content_loc8` = 'Альянс захватил кладбище Двух Шпилей!' WHERE `entry` =10018;
UPDATE `trinity_string` SET `content_loc8` = 'Орда потеряла Западный Маяк!' WHERE `entry` =10019;
UPDATE `trinity_string` SET `content_loc8` = 'Альянс потерял Западный Маяк!' WHERE `entry` =10020;
UPDATE `trinity_string` SET `content_loc8` = 'Орда потеряла Восточный Маяк!' WHERE `entry` =10021;
UPDATE `trinity_string` SET `content_loc8` = 'Альянс потерял Восточный Маяк!' WHERE `entry` =10022;
UPDATE `trinity_string` SET `content_loc8` = 'Орда потеряла кладбище!' WHERE `entry` =10023;
UPDATE `trinity_string` SET `content_loc8` = 'Альянс потерял кладбище!' WHERE `entry` =10024;
UPDATE `trinity_string` SET `content_loc8` = 'Орда захватила Халаа!' WHERE `entry` =10025;
UPDATE `trinity_string` SET `content_loc8` = 'Альянс захватил Халаа!' WHERE `entry` =10026;
UPDATE `trinity_string` SET `content_loc8` = 'Орда потеряла Халаа!' WHERE `entry` =10027;
UPDATE `trinity_string` SET `content_loc8` = 'Альянс потерял Халаа!' WHERE `entry` =10028;
UPDATE `trinity_string` SET `content_loc8` = 'Орда захватила башню Духов!' WHERE `entry` =10029;
UPDATE `trinity_string` SET `content_loc8` = 'Альянс захватил башню Духов!' WHERE `entry` =10030;
UPDATE `trinity_string` SET `content_loc8` = 'Орда потеряла башню Духов!' WHERE `entry` =10031;
UPDATE `trinity_string` SET `content_loc8` = 'Альянс потерял a башню Духов!' WHERE `entry` =10032;
UPDATE `trinity_string` SET `content_loc8` = 'Орда захватила башню Северного перевала!' WHERE `entry` =10033;
UPDATE `trinity_string` SET `content_loc8` = 'Альянс захватил башню Северного перевала!' WHERE `entry` =10034;
UPDATE `trinity_string` SET `content_loc8` = 'Орда захватила Восточную башню!' WHERE `entry` =10035;
UPDATE `trinity_string` SET `content_loc8` = 'Альянс захватил Восточную башню!' WHERE `entry` =10036;
UPDATE `trinity_string` SET `content_loc8` = 'Орда захватила башню Королевской Стражи!' WHERE `entry` =10037;
UPDATE `trinity_string` SET `content_loc8` = 'Альянс захватил башню Королевской Стражи!' WHERE `entry` =10038;
UPDATE `trinity_string` SET `content_loc8` = 'Орда захватила башню Чумного леса!' WHERE `entry` =10039;
UPDATE `trinity_string` SET `content_loc8` = 'Альянс захватил башню Чумного леса!' WHERE `entry` =10040;
UPDATE `trinity_string` SET `content_loc8` = 'Орда потеряла башню Северного перевала!' WHERE `entry` =10041;
UPDATE `trinity_string` SET `content_loc8` = 'Альянс потерял башню Северного перевала!' WHERE `entry` =10042;
UPDATE `trinity_string` SET `content_loc8` = 'Орда потеряла Восточную башню!' WHERE `entry` =10043;
UPDATE `trinity_string` SET `content_loc8` = 'Альянс потерял Восточную башню!' WHERE `entry` =10044;
UPDATE `trinity_string` SET `content_loc8` = 'Орда потеряла башню Королевской Стражи!' WHERE `entry` =10045;
UPDATE `trinity_string` SET `content_loc8` = 'Альянс потерял башню Королевской Стражи!' WHERE `entry` =10046;
UPDATE `trinity_string` SET `content_loc8` = 'Орда потеряла башню Чумного леса!' WHERE `entry` =10047;
UPDATE `trinity_string` SET `content_loc8` = 'Альянс потерял башню Чумного леса!' WHERE `entry` =10048;
UPDATE `trinity_string` SET `content_loc8` = 'Орда собрала 200 силитиста!' WHERE `entry` =10049;
UPDATE `trinity_string` SET `content_loc8` = 'Альянс собрал 200 силитиста!' WHERE `entry` =10050;
UPDATE `trinity_string` SET `content_loc8` = 'Отведите меня к башне Северного перевала.' WHERE `entry` =10051;
UPDATE `trinity_string` SET `content_loc8` = 'Отведите меня к Восточной башне.' WHERE `entry` =10052;
UPDATE `trinity_string` SET `content_loc8` = 'Отведите меня к башне Королевской Стражи.' WHERE `entry` =10053;

UPDATE `trinity_string` SET `content_loc8` = 'Вы были посажены в тюрьму %s на %u час(ов)!' WHERE `entry` =12100;
UPDATE `trinity_string` SET `content_loc8` = '%s написал это как причину: %s' WHERE `entry` =12101;
UPDATE `trinity_string` SET `content_loc8` = '%s посажен вами в тюрьму на %u час(ов).' WHERE `entry` =12102;
UPDATE `trinity_string` SET `content_loc8` = '%s освободил вас из тюрьмы.' WHERE `entry` =12103;
UPDATE `trinity_string` SET `content_loc8` = 'Вы освободили игрока %s из тюрьмы .' WHERE `entry` =12104;
UPDATE `trinity_string` SET `content_loc8` = 'Не указана причина, или причина менее < %u символов!' WHERE `entry` =12105;
UPDATE `trinity_string` SET `content_loc8` = 'Не выбрано имя игрока!' WHERE `entry` =12106;
UPDATE `trinity_string` SET `content_loc8` = 'Не выбран срок наказания!' WHERE `entry` =12107;
UPDATE `trinity_string` SET `content_loc8` = 'Время наказания должно быть между 1 или %u часами!' WHERE `entry` =12108;
UPDATE `trinity_string` SET `content_loc8` = 'Персонаж %s не посажен в тюрьму!' WHERE `entry` =12109;
UPDATE `trinity_string` SET `content_loc8` = 'Эта команда запрещена для персонажей в тюрьме!' WHERE `entry` =12110;
UPDATE `trinity_string` SET `content_loc8` = 'Вам осталось сидеть в тюрьме %u час(ов) и %u минут.' WHERE `entry` =12111;
UPDATE `trinity_string` SET `content_loc8` = 'Вам осталось сидеть в тюрьме %u минут.' WHERE `entry` =12112;
UPDATE `trinity_string` SET `content_loc8` = 'Вы свободны, как птица.. ;-)' WHERE `entry` =12113;
UPDATE `trinity_string` SET `content_loc8` = '%s был посажен в тюрьму %u раз, провел в тюрьме %u минут.\n Последний раз посажен: %s\n Последнее время наказания: %s\nПоследняя причина наказания: %s' WHERE `entry` =12114;
UPDATE `trinity_string` SET `content_loc8` = '%s никогда не сидел.. ' WHERE `entry` =12115;
UPDATE `trinity_string` SET `content_loc8` = 'Вы не можете сами себя посадить в тюрьму!' WHERE `entry` =12116;
UPDATE `trinity_string` SET `content_loc8` = 'Увы, самого себя освободить из тюрьмы невозможно невозможно :(' WHERE `entry` =12117;
UPDATE `trinity_string` SET `content_loc8` = '!!! ВНИМАНИЕ !!!\n Если Вас еще раз посадят в тюрьму, Ваш персонаж будет удален с сервера!' WHERE `entry` =12118;
UPDATE `trinity_string` SET `content_loc8` = 'Персонаж %s был посажен в тюрьму на %u час(ов) гейм-мастером %s \nПричина : %s' WHERE `entry` =12119;
UPDATE `trinity_string` SET `content_loc8` = 'Тюрьма: конфигурация обновилась.' WHERE `entry` =12120;
UPDATE `trinity_string` SET `content_loc8` = 'Тюрьма: Конфигурация загружена.' WHERE `entry` =12121;
UPDATE `trinity_string` SET `content_loc8` = 'Тюрьма: Невозможно загрузить конфигурацию! Таблица пуста или отсутствует! Используйте character_jail.sql!' WHERE `entry` =12122;
UPDATE `trinity_string` SET `content_loc8` = 'Тюрьма: Переменные конфигурации сброшены.' WHERE `entry` =12123;
UPDATE `trinity_string` SET `content_loc8` = 'Персонаж %s (GUID %u) какой-то кореш, телепортировался в тюрьму с кабанчиком.' WHERE `entry` =12124;
UPDATE `trinity_string` SET `content_loc8` = 'Персонаж %s (GUID %u) освобожден из тюряги.' WHERE `entry` =12125;
UPDATE `trinity_string` SET `content_loc8` = 'Персонажа с таким именем здесь не существует!' WHERE `entry` =12126;
UPDATE `trinity_string` SET `content_loc8` = '!!! ВНИМАНИЕ !!!\n Еще один тюремный срок, приведет к бану вашего аккаунта!' WHERE `entry` =12127;
UPDATE `trinity_string` SET `content_loc8` = 'Максимальное время пребывания в тюрьме достигнуто!' WHERE `entry` =12128;
UPDATE `trinity_string` SET `content_loc8` = 'Вы преступник,  однако в данный момент это мера сохранения персонажа.' WHERE `entry` =12129;
UPDATE `trinity_string` SET `content_loc8` = '%s был(а) %u раз в тюрьме, %u час(ов) и %u минут(ы).\nПоследний раз заключен(а) в тюрьму: %s.\nПоследняя тюрьма была: %s\nПоследняя причина была: %s' WHERE `entry` =12130;
UPDATE `trinity_string` SET `content_loc8` = '%s сидел в тюрьме много раз, и уже имеет %u банов! Поставлен штамп в дело - РЕЦЕДИВИСТ.' WHERE `entry` =12131;
UPDATE `trinity_string` SET `content_loc8` = 'Аккаунт этого персонажа блокировался %u!' WHERE `entry` =12132;
UPDATE `trinity_string` SET `content_loc8` = '%s уже сидит..!' WHERE `entry` =12133;
UPDATE `trinity_string` SET `content_loc8` = 'Вы не можете сбросить тюремные записи забаненным аккаунтом!' WHERE `entry` =12134;
UPDATE `trinity_string` SET `content_loc8` = 'Тюрьма: Данные Тюрьмы перечитаны.' WHERE `entry` =12135;
UPDATE `trinity_string` SET `content_loc8` = 'Тюрьма: Удаление записей о несуществующих более персонажей.' WHERE `entry` =12136;
UPDATE `trinity_string` SET `content_loc8` = 'Тюрьма: Проверка на устаревшие наказания...' WHERE `entry` =12137;
UPDATE `trinity_string` SET `content_loc8` = 'Тюрьма: Не найдено наказания.' WHERE `entry` =12138;
UPDATE `trinity_string` SET `content_loc8` = 'Тюрьма: %u устаревшее наказание найдено и %u ms проверено.' WHERE `entry` =12139;
UPDATE `trinity_string` SET `content_loc8` = 'Тюрьма: Инициализируем Тюрягу...' WHERE `entry` =12140;
UPDATE `trinity_string` SET `content_loc8` = 'Тюрьма: Тюрьма не активна! Отмена инициализации.' WHERE `entry` =12141;
UPDATE `trinity_string` SET `content_loc8` = 'Тюрьма: осуждения не найдено.' WHERE `entry` =12142;
UPDATE `trinity_string` SET `content_loc8` = 'Тюрьма: %u арест(ов) (%u активных) в %u ms загружены.' WHERE `entry` =12143;
UPDATE `trinity_string` SET `content_loc8` = 'ОШИБКА, строка слишком длинная!' WHERE `entry` =12144;
UPDATE `trinity_string` SET `content_loc8` = 'Тюрьма: данные загружены.' WHERE `entry` =12145;
UPDATE `trinity_string` SET `content_loc8` = 'Нет данной фракции (horde/ally)! ' WHERE `entry` =12146;
UPDATE `trinity_string` SET `content_loc8` = 'Тюрьма активирована.' WHERE `entry` =12197;
UPDATE `trinity_string` SET `content_loc8` = 'Тюрьма деактивирована.' WHERE `entry` =12198;
UPDATE `trinity_string` SET `content_loc8` = 'Тюрьма не активирована!' WHERE `entry` =12199;

UPDATE `trinity_string` SET `content_loc8` = 'Персонаж %s $gисключен:исключена; с игрового мира.' WHERE `entry` =282;